/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendance;

import static attendance.TrackAttendance.d;
import static attendance.TrackAttendance.dateSelected;
import static attendance.TrackAttendance.username;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author priyamvora
 */
public class TrackPracAttendance extends javax.swing.JFrame {
    static String username;
    DbConnect db;
    Connection conn;
    static String fid,dateSelected,batch;
    ResultSet rs;
    Date d;
    boolean dateSelectedFlag=false,batchSelectedFlag=false;
    String sql="";
    ResultSetOperations rso;
    int presentCount=0,absentCount=0,totalCount=0;
    float presentPercent=0.0f,absentPercent=0.0f;
    ArrayList<String>arr;
    /**
     * Creates new form TrackPracAttendance
     */
    public void setUsername(){
        usernameLabel.setText("Welcome "+username);
    }
    public TrackPracAttendance() {
        initComponents();
    }
    public TrackPracAttendance(String username){
        this.username=username;
       
        
    }
    public void populateBatchCombo(){
        try {
            
            db=new DbConnect();
            conn=db.getConn();
            rso=new ResultSetOperations(username);
            sql="Select fid from faculty where name='"+username+"'";
            
            fid=rso.getFid(conn, sql);
            sql="Select bid from faculty_batch where fid='"+fid+"'";
            rs=rso.getBatch(conn, sql);
            batchCombo.addItem("Select");
            arr=new ArrayList<String>();
            while(rs.next()){
             
             batchCombo.addItem(rs.getString("bid").toUpperCase());
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
    public void displayTabelOnPanel(){
         DbConnect db=new DbConnect();
        Connection conn=db.getConn();
        ResultSetOperations rso=new ResultSetOperations(username);
        
            
            
            try {
                
                String sql="Select date,sapid,status,batch from prac where fid='"+fid+"'order by sapid,date desc";
                System.out.println(sql);
                
                ResultSet rs=rso.populatePracTable(conn, sql);
                System.out.println("Value returned");
                rs.beforeFirst();
                
                pracTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
                pracTable.setModel(DbUtils.resultSetToTableModel(rs));
                rs.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            
                
            
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        takeAttendanceButton = new javax.swing.JButton();
        trackAttendanceButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        theoryButton = new javax.swing.JButton();
        pracicalButton = new javax.swing.JButton();
        moreButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        batchCombo = new javax.swing.JComboBox<>();
        goButton = new javax.swing.JButton();
        batchPieChartPanel = new javax.swing.JPanel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pracTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(900, 145));

        takeAttendanceButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        takeAttendanceButton.setText("   Take Attendance   ");
        takeAttendanceButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(60, 60, 60, 60));
        takeAttendanceButton.setFocusable(false);
        takeAttendanceButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        takeAttendanceButton.setPreferredSize(new java.awt.Dimension(300, 50));
        takeAttendanceButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        takeAttendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeAttendanceButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(takeAttendanceButton);

        trackAttendanceButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        trackAttendanceButton.setText("Track Attendance");
        trackAttendanceButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(60, 60, 60, 60));
        trackAttendanceButton.setFocusable(false);
        trackAttendanceButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        trackAttendanceButton.setPreferredSize(new java.awt.Dimension(300, 50));
        trackAttendanceButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        trackAttendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackAttendanceButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(trackAttendanceButton);

        usernameLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        usernameLabel.setText("Hi,Neha.Katre");
        usernameLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 45, 10, 30));
        usernameLabel.setMaximumSize(new java.awt.Dimension(298, 41));
        usernameLabel.setPreferredSize(new java.awt.Dimension(600, 41));
        jToolBar1.add(usernameLabel);

        logoutButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        logoutButton.setFocusable(false);
        logoutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutButton.setPreferredSize(new java.awt.Dimension(200, 50));
        logoutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(logoutButton);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setMaximumSize(new java.awt.Dimension(900, 145));
        jToolBar2.setMinimumSize(new java.awt.Dimension(738, 145));
        jToolBar2.setPreferredSize(new java.awt.Dimension(900, 145));

        theoryButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        theoryButton.setText("Theory");
        theoryButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(60, 60, 60, 60));
        theoryButton.setFocusable(false);
        theoryButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        theoryButton.setPreferredSize(new java.awt.Dimension(300, 50));
        theoryButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        theoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theoryButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(theoryButton);

        pracicalButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pracicalButton.setText("Practical");
        pracicalButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(60, 60, 60, 60));
        pracicalButton.setFocusable(false);
        pracicalButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pracicalButton.setPreferredSize(new java.awt.Dimension(300, 50));
        pracicalButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(pracicalButton);

        moreButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        moreButton.setText("Export Practical Attendance");
        moreButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(60, 60, 60, 60));
        moreButton.setFocusable(false);
        moreButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        moreButton.setPreferredSize(new java.awt.Dimension(370, 50));
        moreButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        moreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(moreButton);

        batchCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                batchComboItemStateChanged(evt);
            }
        });

        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout batchPieChartPanelLayout = new javax.swing.GroupLayout(batchPieChartPanel);
        batchPieChartPanel.setLayout(batchPieChartPanelLayout);
        batchPieChartPanelLayout.setHorizontalGroup(
            batchPieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        batchPieChartPanelLayout.setVerticalGroup(
            batchPieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(batchPieChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(batchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(goButton, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goButton)
                    .addComponent(batchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(batchPieChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pracTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pracTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pracTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Sap", "Status", "Batch"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        pracTable.setRowHeight(60);
        jScrollPane1.setViewportView(pracTable);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1193, Short.MAX_VALUE)
                            .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void takeAttendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeAttendanceButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TakeAttendanceFrame.main(null);
    }//GEN-LAST:event_takeAttendanceButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:

        int op=JOptionPane.showConfirmDialog(this,"Are you sure you want to logout?");
        if(op==0){
            this.dispose();
            LoginFrame.main(null);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void theoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theoryButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TrackAttendance.main(null);
    }//GEN-LAST:event_theoryButtonActionPerformed

    private void moreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreButtonActionPerformed
        // TODO add your handling code here:
        new ExportToText(pracTable,2);
        

    }//GEN-LAST:event_moreButtonActionPerformed

    private void trackAttendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackAttendanceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trackAttendanceButtonActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // TODO add your handling code here:
        if(!batchSelectedFlag){
            JOptionPane.showMessageDialog(this,"Select a batch","Alert",JOptionPane.ERROR_MESSAGE);
            
        }else{
             db=new DbConnect();
            conn=db.getConn();
            ResultSetOperations rso=new ResultSetOperations(username); 
            batchPieChartPanel.setVisible(false);
            String table=batch;
            
            String present="Present";
            sql="Select count(*) as pracCount from "+table+" where fid='"+fid+"'";
            rso.setPracCount(conn, sql);
            sql="Select count(status) as pracPresentCount from "+table+" where fid ='"+fid+"'"+" and status='"+present+"'";
            System.out.println(sql);
            
            presentCount=rso.returnPracPresentCount(conn, sql);
            absentCount=rso.returnPracAbsentCount();
            totalCount=presentCount+absentCount;
            presentPercent=((float)presentCount*100)/totalCount;
            absentPercent=100.00f-presentPercent;
            System.out.println(presentPercent);
            System.out.println(absentPercent);
            batchPieChartPanel.setVisible(true);
            batchPieChartPanel.removeAll();
            PieChart pc=new PieChart("","Average Present Absent ratio of  "+batch.toUpperCase(),batchPieChartPanel,presentPercent,absentPercent,2);
            
            
        }
    }//GEN-LAST:event_goButtonActionPerformed

    private void batchComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_batchComboItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==ItemEvent.SELECTED){
          batch=(String)batchCombo.getSelectedItem();
           
           if(batch.equals("Select")){
               batchSelectedFlag=false;
           }else{
               batchSelectedFlag=true;
               batch=batch.toLowerCase();
           }
        }
    }//GEN-LAST:event_batchComboItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackPracAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackPracAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackPracAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackPracAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                TrackPracAttendance trpratt=new TrackPracAttendance();
                trpratt.setVisible(true);
                trpratt.setUsername();
                trpratt.populateBatchCombo();
                trpratt.setExtendedState(JFrame.MAXIMIZED_BOTH);
                                trpratt.displayTabelOnPanel();
                trpratt.setResizable(false);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> batchCombo;
    private static javax.swing.JPanel batchPieChartPanel;
    private javax.swing.JButton goButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton moreButton;
    private javax.swing.JTable pracTable;
    private javax.swing.JButton pracicalButton;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JButton takeAttendanceButton;
    private javax.swing.JButton theoryButton;
    private javax.swing.JButton trackAttendanceButton;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
