/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendance;

import static attendance.TakeAttendanceFrame.username;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author priyamvora
 */
public class TrackAttendance extends javax.swing.JFrame {
    static String username,fid;
    
    /**
     * Creates new form TrackAttendance
     */
    public TrackAttendance() {
        initComponents();
        
    }
    TrackAttendance(String username){
        this.username=username;
    }
    public void setUsername(){
        usernameLabel.setText("Welcome "+username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        takeAttendanceButton = new javax.swing.JButton();
        trackAttendanceButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jsp = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        barChartPanel = new javax.swing.JPanel();
        pieChartPanel = new javax.swing.JPanel();
        pieChart1Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(894, 638));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(900, 145));
        jToolBar1.setMinimumSize(new java.awt.Dimension(783, 145));
        jToolBar1.setPreferredSize(new java.awt.Dimension(900, 145));

        takeAttendanceButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        takeAttendanceButton.setText("   Take Attendance   ");
        takeAttendanceButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(60, 60, 60, 60));
        takeAttendanceButton.setFocusable(false);
        takeAttendanceButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        takeAttendanceButton.setPreferredSize(new java.awt.Dimension(300, 50));
        takeAttendanceButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        takeAttendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeAttendanceButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(takeAttendanceButton);

        trackAttendanceButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        trackAttendanceButton.setText("Track Attendance");
        trackAttendanceButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(60, 60, 60, 60));
        trackAttendanceButton.setFocusable(false);
        trackAttendanceButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        trackAttendanceButton.setPreferredSize(new java.awt.Dimension(300, 50));
        trackAttendanceButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(trackAttendanceButton);

        usernameLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        usernameLabel.setText("Hi,Neha.Katre");
        usernameLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 45, 10, 30));
        usernameLabel.setMaximumSize(new java.awt.Dimension(298, 41));
        usernameLabel.setPreferredSize(new java.awt.Dimension(600, 41));
        jToolBar1.add(usernameLabel);

        logoutButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        logoutButton.setFocusable(false);
        logoutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutButton.setPreferredSize(new java.awt.Dimension(200, 50));
        logoutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(logoutButton);

        tablePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tablePanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Sap-Id", "Present/Absent", "Theory/Practical"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(3);
        jTable1.setShowGrid(true);
        jsp.setViewportView(jTable1);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout barChartPanelLayout = new javax.swing.GroupLayout(barChartPanel);
        barChartPanel.setLayout(barChartPanelLayout);
        barChartPanelLayout.setHorizontalGroup(
            barChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barChartPanelLayout.setVerticalGroup(
            barChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pieChartPanelLayout = new javax.swing.GroupLayout(pieChartPanel);
        pieChartPanel.setLayout(pieChartPanelLayout);
        pieChartPanelLayout.setHorizontalGroup(
            pieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );
        pieChartPanelLayout.setVerticalGroup(
            pieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pieChart1PanelLayout = new javax.swing.GroupLayout(pieChart1Panel);
        pieChart1Panel.setLayout(pieChart1PanelLayout);
        pieChart1PanelLayout.setHorizontalGroup(
            pieChart1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );
        pieChart1PanelLayout.setVerticalGroup(
            pieChart1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pieChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pieChart1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(barChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pieChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pieChart1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:

        int op=JOptionPane.showConfirmDialog(this,"Are you sure you want to logout?");
        if(op==0){
            this.dispose();
            LoginFrame.main(null);
        }

    }//GEN-LAST:event_logoutButtonActionPerformed
    public void displayTableOnPanel(JFrame jframe){
        DbConnect db=new DbConnect();
        Connection conn=db.getConn();
       String sql="Select fid from faculty where name='"+username+"'";
       ResultSetOperations rso=new ResultSetOperations(username);
       fid=rso.getFid(conn, sql);
       sql="Select sapid,date,status from attendance where fid='"+fid+"'order by sapid,date DESC";
       ResultSet attendanceResultSet=rso.populateTable(conn, sql);
       jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
       jTable1.setModel(DbUtils.resultSetToTableModel(attendanceResultSet));
       
       
       
       
        
    }
    private void takeAttendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeAttendanceButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TakeAttendanceFrame.main(null);
    }//GEN-LAST:event_takeAttendanceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 TrackAttendance trAtt=new TrackAttendance();
                 trAtt.setVisible(true);
                 trAtt.setUsername();
                 trAtt.setLocationRelativeTo(null);
                 trAtt.setExtendedState(JFrame.MAXIMIZED_BOTH);
                 
                 trAtt.displayTableOnPanel(trAtt);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barChartPanel;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel pieChart1Panel;
    private javax.swing.JPanel pieChartPanel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JButton takeAttendanceButton;
    private javax.swing.JButton trackAttendanceButton;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
